image: golang:1.8

stages:
  - build

variables:
  GOSOURCES: "/go/src/gitlab.com/TLSProxy"

tlsproxy-build:
  stage: build
  script:
    - mkdir -p $GOSOURCES
    - cd $GOSOURCES
    - ln -s $CI_PROJECT_DIR TLSProxy
    - cd $GOSOURCES/TLSProxy
    - curl https://glide.sh/get | sh
    - glide install
    - go build -ldflags "-X main.Build=$CI_PIPELINE_ID -X main.Tag=$CI_BUILD_TAG"
  