services:
  tlsproxy:
    build: .
    ports:
      - "443:443"
    environment:
      - WHITELIST=www.example.com
      - EMAIL=you@example.com
      - BACKEND=http://web:80
      - HTTP=true
      - HAR=true
    volumes:
      - certs-volume:/root/certs
    depends_on:
      - web

  web:
    image: "mendhak/http-https-echo"
    environment:
      - HTTP_PORT=80

volumes:
  certs-volume:
