version: '3'

services:
  tlsproxy:
    build: .
    ports:
      - "443:443"
    environment:
      - WHITELIST=code.sslping.com
      - EMAIL=chris@chris-hartwig.com
      - BACKEND=http://web:80
      - HTTP=true
      - HAR=true
    volumes:
      - certs-volume:/root/certs
    depends_on:
      - web

  web:
    image: "mendhak/http-https-echo"
    ports:
      - "9099:80"
      
volumes:
  certs-volume: